---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-app-2-repo
  namespace: assemble-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/jaland/quarkus-getting-started.git-gitops